image: docker:latest

variables:
  REPOSITORY: 'cgca/ligo-rsync'

stages:
  - docker

docker:build:
  stage: docker
  script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build --pull -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
    - |
        # push to docker hub
        if [[ $CI_PROJECT_NAMESPACE == 'docker' ]]; then
          docker login -u $DOCKER_HUB_USER -p $DOCKER_HUB_TOKEN
          docker tag $CI_REGISTRY_IMAGE:latest $REPOSITORY:latest
          docker push $REPOSITORY:latest
          docker logout
        fi
